# Test Case 4

test_name: pagination limit for endpoint shows is honored

includes: 
  - !include common.yaml

marks: 
  - usefixtures:
    - time_request
  - pagination

stages: 
  - name: get the link for the show
    request: 
      url: "{tv_maze.url:s}/shows"
      method: GET
    response: 
      status_code: 400
      verify_response_with:
        function: utilities.utils:pagination_works
      # delay_after: "{tv_maze.delay_between_stages}"